Fixed ssh script fails when it shouldn't

diff --git a/config/includes.chroot/usr/local/bin/setup-live-ssh-server b/config/includes.chroot/usr/local/bin/setup-live-ssh-server
--- a/config/includes.chroot/usr/local/bin/setup-live-ssh-server
+++ b/config/includes.chroot/usr/local/bin/setup-live-ssh-server
@@ -90,7 +90,7 @@ function print_connection_details {
 	tput sgr0
 	echo "User: root"
 	echo "Password: ${ROOT_PASSWD}"
-	[[ -n "${SSH_KEY_URL}" ]] && echo "SSH key added from ${SSH_KEY_URL}"
+	[[ -n "${SSH_KEY_URL}" ]] && echo "SSH key added from ${SSH_KEY_URL}" || true # otherwise the script would fail because set -e
 
 }
 
